package watersupply;
// Generated Mar 23, 2017 10:27:58 PM by Hibernate Tools 4.3.1



/**
 * Municipality generated by hbm2java
 */
public class Municipality  implements java.io.Serializable {


     private Integer municipalityId;
     private long population;

    public Municipality() {
    }

    public Municipality(long population) {
       this.population = population;
    }
   
    public Integer getMunicipalityId() {
        return this.municipalityId;
    }
    
    public void setMunicipalityId(Integer municipalityId) {
        this.municipalityId = municipalityId;
    }
    public long getPopulation() {
        return this.population;
    }
    
    public void setPopulation(long population) {
        this.population = population;
    }




}


