package watersupply;
// Generated Mar 23, 2017 10:27:58 PM by Hibernate Tools 4.3.1



/**
 * Sampling generated by hbm2java
 */
public class Sampling  implements java.io.Serializable {


     private int samplingId;
     private double value;
     private double uncertainty;
     private String method;
     private double limits;

    public Sampling() {
    }

    public Sampling(int samplingId, double value, double uncertainty, String method, double limits) {
       this.samplingId = samplingId;
       this.value = value;
       this.uncertainty = uncertainty;
       this.method = method;
       this.limits = limits;
    }
   
    public int getSamplingId() {
        return this.samplingId;
    }
    
    public void setSamplingId(int samplingId) {
        this.samplingId = samplingId;
    }
    public double getValue() {
        return this.value;
    }
    
    public void setValue(double value) {
        this.value = value;
    }
    public double getUncertainty() {
        return this.uncertainty;
    }
    
    public void setUncertainty(double uncertainty) {
        this.uncertainty = uncertainty;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public double getLimits() {
        return this.limits;
    }
    
    public void setLimits(double limits) {
        this.limits = limits;
    }




}


