package watersupply;
// Generated Mar 23, 2017 10:27:58 PM by Hibernate Tools 4.3.1



/**
 * SwsSamplingId generated by hbm2java
 */
public class SwsSamplingId  implements java.io.Serializable {


     private int fkSamplingId;
     private int fkSwsid;

    public SwsSamplingId() {
    }

    public SwsSamplingId(int fkSamplingId, int fkSwsid) {
       this.fkSamplingId = fkSamplingId;
       this.fkSwsid = fkSwsid;
    }
   
    public int getFkSamplingId() {
        return this.fkSamplingId;
    }
    
    public void setFkSamplingId(int fkSamplingId) {
        this.fkSamplingId = fkSamplingId;
    }
    public int getFkSwsid() {
        return this.fkSwsid;
    }
    
    public void setFkSwsid(int fkSwsid) {
        this.fkSwsid = fkSwsid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SwsSamplingId) ) return false;
		 SwsSamplingId castOther = ( SwsSamplingId ) other; 
         
		 return (this.getFkSamplingId()==castOther.getFkSamplingId())
 && (this.getFkSwsid()==castOther.getFkSwsid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkSamplingId();
         result = 37 * result + this.getFkSwsid();
         return result;
   }   


}


