package watersupply;
// Generated Mar 23, 2017 10:27:58 PM by Hibernate Tools 4.3.1



/**
 * SwsSampling generated by hbm2java
 */
public class SwsSampling  implements java.io.Serializable {


     private SwsSamplingId id;

    public SwsSampling() {
    }

    public SwsSampling(SwsSamplingId id) {
       this.id = id;
    }
   
    public SwsSamplingId getId() {
        return this.id;
    }
    
    public void setId(SwsSamplingId id) {
        this.id = id;
    }




}


